---
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
        files: ^(?:core/(?:src|include|test)|ui-cpp/)
        exclude:
          ^(?:core/test/catch.hpp$|ui-cpp/(?:|ui-imgui/|ui-qt/)thirdparty/)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: core/python
