from spirit import simulation, state,quantities, hamiltonian,parameters,geometry,configuration,system,io
import numpy as np
import os
import matplotlib.pyplot as plt
import multiprocessing as mp
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
from scipy.stats import linregress
from tqdm import tqdm
import plotly.colors as pc
import time
import glob
from datetime import timedelta
from collections import defaultdict

def plot_loop(gamma):
    iterations_per_step = 1  #Spin glass, Take this many Metropolis iterations per lattice site between each check for convergence
    output_interval = 3  # Interval at which spin configuration files are saved
    fn = "dipolar_arr"
    prefix = "DDI_exp_14_G0p00005_Ht10p0"

    mu = 7
    dim = 10
    concentration = 20
    H_steps_1 = 10
    H_steps_3 = 10

    H_high = 6.0
    H_low = 3.0

    relax_steps_0 = 10

    path_arr_x = os.path.join(f"dipolar_interaction_matrices_reordered/{dim}_{dim}_{dim}/",
                              fn + "_x.npy")  # fn = dipolar_arr
    path_arr_y = os.path.join(f"dipolar_interaction_matrices_reordered/{dim}_{dim}_{dim}/", fn + "_y.npy")
    path_arr_z = os.path.join(f"dipolar_interaction_matrices_reordered/{dim}_{dim}_{dim}/", fn + "_z.npy")

    if os.path.exists(path_arr_x) and os.path.exists(path_arr_y) and os.path.exists(path_arr_z):
        tqdm.write("loading DDI interaction data.")
        DDI_interaction_x = np.load(path_arr_x)
        DDI_interaction_y = np.load(path_arr_y)
        DDI_interaction_z = np.load(path_arr_z)
    else:
        tqdm.write("DDI files not found")
    #        break

    with state.State(f"input/LHF_DDI_glass_14_{concentration}_tunnel_{dim}.cfg", quiet = True) as p_state:
        types = geometry.get_atom_types(p_state)
        nos = types.size
        # tqdm.write(f"Sites: {nos}  Spins: {nos+np.sum(types)}")
        locs = geometry.get_positions(p_state)
        np.savetxt("output/"+prefix+"atom_locs.csv",locs,delimiter=",")
        np.savetxt("output/"+prefix+"atom_types.csv",types,delimiter=",")
    #    write_config(p_state,prefix)
        parameters.mc.set_metropolis_cone(p_state,use_cone=True,cone_angle=30,use_adaptive_cone=True)
        parameters.mc.set_metropolis_spinflip(p_state,False)

        parameters.mc.set_tunneling_gamma(p_state, tunneling_gamma=gamma)

        #We'll evaluate convergence after enough Metropolis steps to hit each site twice on average
        parameters.mc.set_iterations(p_state,iterations_per_step*types.size,iterations_per_step*types.size)

        #Initialize from unordered state
        configuration.random(p_state)


    #Filter out any vacant sites
        vacancies_idx_tuple = np.where(types == -1)
        vacancies_idx = vacancies_idx_tuple[0]

        locs[:,0][vacancies_idx] = 0
        locs[:,1][vacancies_idx] = 0
        locs[:,2][vacancies_idx] = 0

        Hts_randomise = [8]*relax_steps_0
        #In Steven's paper sample was relaxed at high transverse field before negative
        # field cycle, probably to randomise the spins. But we should do this here anyways so config generated by configuration.random() align roughly along z-axis

        for i,Ht in enumerate(Hts_randomise):

            Hmag = Ht
            hamiltonian.set_field(p_state,Hmag,(Ht,0,0)) #Inside set_field, the vector is normalized, so we don't have to do that here

            spins = system.get_spin_directions(p_state)  #Get the current spin state to update the DDI fields from the Ewald sum
            spins[:, 2][vacancies_idx] = 0   #For LHF, we only care about Sz, but zero out the moments for vacancy site
            spins[:, 1][vacancies_idx] = 0
            spins[:, 0][vacancies_idx] = 0
            #Calculate the DDI field components, and then send to the SPIRIT engine. DDI interaction calculations are in Oe, SPIRIT
            #uses T, so need to scale accordingly.
            #Get the field at each spin.
            #V_xz = V_zx.T etc

            DDI_field_x_from_z = np.matmul(DDI_interaction_x,spins[:,2]) *7/1e4 #V_xz
            DDI_field_y_from_z = np.matmul(DDI_interaction_y,spins[:,2]) *7/1e4 #V_yz
            DDI_field_z_from_z = np.matmul(DDI_interaction_z,spins[:,2]) *7/1e4 #V_zz

            DDI_field_z_from_y = np.matmul(DDI_interaction_y.T, spins[:, 1]) * 7 / 1e4 #V_zy

            DDI_field_z_from_x = np.matmul(DDI_interaction_x.T, spins[:, 0]) * 7 / 1e4 #V_zx

            DDI_field_z_total = DDI_field_z_from_z + DDI_field_z_from_y + DDI_field_z_from_x

            #Pass into SPIRIT
            DDI_field_interleave = np.ravel(np.column_stack((DDI_field_x_from_z,DDI_field_y_from_z,DDI_field_z_total)))
            system.set_DDI_field(p_state,n_atoms=nos,ddi_fields=DDI_field_interleave)


            # for j in range(converge_max):
            simulation.start(p_state, simulation.METHOD_MC, single_shot=False) #solver_type=simulation.MC_ALGORITHM_METROPOLIS
            simulation.stop(p_state)


        # Hts = [H_relax]*H_relax_steps
        H1 = [H_high]*H_steps_1
        H2 = [H_low]*H_steps_1
        H3 = [H_high]*H_steps_3

        Hts = H1 + H2 + H3

        correlations = []

        count = 0
        for k,Ht in enumerate(Hts):
            count+=1
            tqdm.write(f'Ht: {Ht:.3f}, count: {count} gamma: {gamma} concentration: {concentration}')

            hamiltonian.set_field(p_state,Ht,(Ht,0,0)) #Inside set_field, the vector is normalized, so we don't have to do that here

            spins = system.get_spin_directions(p_state)  #Get the current spin state to update the DDI fields from the Ewald sum
            spins[:, 2][vacancies_idx] = 0   #For LHF, we only care about Sz, but zero out the moments for vacancy site
            spins[:, 1][vacancies_idx] = 0
            spins[:, 0][vacancies_idx] = 0
            #Calculate the DDI field components, and then send to the SPIRIT engine. DDI interaction calculations are in Oe, SPIRIT
            #uses T, so need to scale accordingly.
            #Get the field at each spin.
            #V_xz = V_zx.T etc

            DDI_field_x_from_z = np.matmul(DDI_interaction_x,spins[:,2]) *7/1e4 #V_xz
            DDI_field_y_from_z = np.matmul(DDI_interaction_y,spins[:,2]) *7/1e4 #V_yz
            DDI_field_z_from_z = np.matmul(DDI_interaction_z,spins[:,2]) *7/1e4 #V_zz

            DDI_field_z_from_y = np.matmul(DDI_interaction_y.T, spins[:, 1]) * 7 / 1e4 #V_zy

            DDI_field_z_from_x = np.matmul(DDI_interaction_x.T, spins[:, 0]) * 7 / 1e4 #V_zx

            DDI_field_z_total = DDI_field_z_from_z + DDI_field_z_from_y + DDI_field_z_from_x

            #Pass into SPIRIT
            DDI_field_interleave = np.ravel(np.column_stack((DDI_field_x_from_z,DDI_field_y_from_z,DDI_field_z_total)))
            system.set_DDI_field(p_state,n_atoms=nos,ddi_fields=DDI_field_interleave)


            simulation.start(p_state, simulation.METHOD_MC, single_shot=False) #solver_type=simulation.MC_ALGORITHM_METROPOLIS
            simulation.stop(p_state)

            if k == H_steps_1 - 1 :
                #End of first stage
                spins = system.get_spin_directions(p_state)
                spin_z_before = spins[:,2]

                # Remove vacant site data from output arrays
                valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)

                spin_z_before = spin_z_before[valid_idx]

            if k>=H_steps_1:
                spins = system.get_spin_directions(p_state)
                spin_z_after = spins[:, 2]

                # Remove vacant site data from output arrays
                valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)

                spin_z_after = spin_z_after[valid_idx]

                corr = np.corrcoef(spin_z_before, spin_z_after)[0, 1]

            # Define both options
            Bfields_positive = np.arange(0, 0.4, 0.1)
            Bfields_negative = np.arange(0, -0.4, -0.1)

            # Randomly choose one, to avoid always polarising spins in one direction
            Bfields = Bfields_positive if np.random.rand() < 0.5 else Bfields_negative


            #In this case don't need susceptibility, but just run this code to avoid changing the conditions e.g. number of MC iterations
            for i, HzB in enumerate(Bfields):
                # tqdm.write(f'Hz: {Hz:.3f}', concentration)

                Hmag = np.sqrt(HzB * HzB + Ht * Ht)
                hamiltonian.set_field(p_state, Hmag, (Ht, 0,
                                                      HzB))  # Inside set_field, the vector is normalized, so we don't have to do that here

                spins = system.get_spin_directions(
                    p_state)  # Get the current spin p_state to update the DDI fields from the Ewald sum
                spins[:, 2][vacancies_idx] = 0  # For LHF, we only care about Sz, but zero out the moments for vacancy site
                spins[:, 1][vacancies_idx] = 0
                spins[:, 0][vacancies_idx] = 0

                # Calculate the DDI field components, and then send to the SPIRIT engine. DDI interaction calculations are in Oe, SPIRIT
                # uses T, so need to scale accordingly.
                # Get the field at each spin.
                DDI_field_x_from_z = np.matmul(DDI_interaction_x, spins[:, 2]) * 7 / 1e4  # V_xz
                DDI_field_y_from_z = np.matmul(DDI_interaction_y, spins[:, 2]) * 7 / 1e4  # V_yz
                DDI_field_z_from_z = np.matmul(DDI_interaction_z, spins[:, 2]) * 7 / 1e4  # V_zz

                DDI_field_z_from_y = np.matmul(DDI_interaction_y.T, spins[:, 1]) * 7 / 1e4  # V_zy

                DDI_field_z_from_x = np.matmul(DDI_interaction_x.T, spins[:, 0]) * 7 / 1e4  # V_zx

                DDI_field_z_total = DDI_field_z_from_z + DDI_field_z_from_y + DDI_field_z_from_x

                # Pass into SPIRIT
                DDI_field_interleave = np.ravel(
                    np.column_stack((DDI_field_x_from_z, DDI_field_y_from_z, DDI_field_z_total)))
                system.set_DDI_field(p_state, n_atoms=nos, ddi_fields=DDI_field_interleave)

                # converge_threshold = 0.01  # Fractional change in magnetization between steps to accept convergence
                converge_threshold = 0.000000001
                converge_max = 1  # Maximum number of steps to take before moving on
                if i != 0:  # i = 0 state already went through one round of convergence before entering susceptibility loop
                    # Check convergence, same as old hysteresis_loop. But METHOD_MC now uses tunnelling since we set tunnel flag to 1 in cfg files
                    for j in range(converge_max):
                        simulation.start(p_state, simulation.METHOD_MC,
                                         single_shot=False)  # solver_type=simulation.MC_ALGORITHM_METROPOLIS
                        simulation.stop(p_state)
                        if j == 0:
                            m_temp = quantities.get_magnetization(p_state)[2]
                        else:
                            m_prev = m_temp
                            m_temp = quantities.get_magnetization(p_state)[2]
                            #               ratio = abs((m_temp-m_prev)/m_prev)
                            ratio = abs((m_temp - m_prev) / mu)
                            tqdm.write(
                                f"########Susceptibility measurement: Iteration: {j:d}, Convergence: {ratio:.4f}, M_z: {m_temp:.4f}")
                            if ratio < converge_threshold:
                                break

                if k >= H_steps_1:
                    spins = system.get_spin_directions(p_state)
                    spin_z_after = spins[:, 2]

                    # Remove vacant site data from output arrays
                    valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)
                    spin_z_after = spin_z_after[valid_idx]

                    # Keep only pairs where both |before| <= 1 and |after| <= 1
                    mask = (np.abs(spin_z_before) <= 1) & (np.abs(spin_z_after) <= 1)
                    filtered_before = spin_z_before[mask]
                    filtered_after = spin_z_after[mask]

                    if filtered_before.size > 1 and filtered_after.size > 1:
                        corr += np.corrcoef(filtered_before, filtered_after)[0, 1]
                    else:
                        corr += np.nan  # or 0.0, depending on how you want to handle it

            if k >= H_steps_1:
                correlations.append((k, corr/(len(Bfields)+1))) #take corr measurement everytime

        return correlations


if __name__ == '__main__':
    start_time = time.time()  # Start timer
    mp.set_start_method("spawn", force=True)

    n_cycles = 120

    H_high = 6.0
    H_low = 3.0

    dim = 10
    concentration = 20
    # gamma = 0.000001
    gamma = 1e-7
    gammas = [gamma]*n_cycles
    anisotropy = 1.5

    with mp.Pool(processes=mp.cpu_count()) as pool:
        results = list(tqdm(pool.imap_unordered(plot_loop, gammas), total=len(gammas), desc="Running simulations"))

    # Flatten results
    flat_results = [pair for sublist in results for pair in sublist]

    # Create DataFrame
    df = pd.DataFrame(flat_results, columns=['k', 'corr'])

    df.to_csv(f"40_decay_correlations_negative_field_cycle_dim{dim}_anisotropy{anisotropy}_ncycles{n_cycles}_gamma{gamma}_H_high{H_high}_H_low{H_low}.csv", index=False)

    # Remove NaN correlations before saving/averaging
    df = df.dropna(subset=['corr'])

    # Group by k and compute stats
    grouped = df.groupby('k')['corr'].agg(['mean', 'std']).reset_index()
    # grouped['sem'] = grouped['std'] / np.sqrt(grouped['count'])
    grouped['sem'] = grouped['std'] / np.sqrt(n_cycles)

    # Rename for plotting
    grouped.rename(columns={'mean': 'corr_avg'}, inplace=True)

    # Plot with error bars
    fig = px.line(
        grouped,
        x='k',
        y='corr_avg',
        error_y='sem',
        markers=True,
        title=f"Average Correlation vs. k, H_high = {H_high}, H_low = {H_low}",
        labels={'k': 'k', 'corr_avg': 'Average Correlation'}
    )

    fig.write_html(f"40_decay_correlations_negative_field_cycle_dim{dim}_anisotropy{anisotropy}_ncycles{n_cycles}_gamma{gamma}_H_high{H_high}_H_low{H_low}.html")


