from spirit import simulation, state,quantities, hamiltonian,parameters,geometry,configuration,system,io
import numpy as np
import os
import matplotlib.pyplot as plt
import multiprocessing as mp
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
from scipy.stats import linregress
from tqdm import tqdm
import plotly.colors as pc
import time
from scipy.stats import gaussian_kde
import glob
from datetime import timedelta
from collections import defaultdict

def plot_loop(gamma):
    iterations_per_step = 1  #Spin glass, Take this many Metropolis iterationss per lattice site between each check for convergence
    output_interval = 3  # Interval at which spin configuration files are saved
    fn = "dipolar_arr"
    prefix = "DDI_exp_14_G0p00005_Ht10p0"

    H_relax = 1.8
    mu = 7
    dim = 4
    concentration = 20

    H_steps_1 = 20
    H_steps_3 = 10 #Just take spins right after rejuvenation

    H_high = 4.0
    H_low = 2.0

    relax_steps_0 = 10

    path_arr_x = os.path.join(f"dipolar_interaction_matrices_reordered/{dim}_{dim}_{dim}/",
                              fn + "_x.npy")  # fn = dipolar_arr
    path_arr_y = os.path.join(f"dipolar_interaction_matrices_reordered/{dim}_{dim}_{dim}/", fn + "_y.npy")
    path_arr_z = os.path.join(f"dipolar_interaction_matrices_reordered/{dim}_{dim}_{dim}/", fn + "_z.npy")

    if os.path.exists(path_arr_x) and os.path.exists(path_arr_y) and os.path.exists(path_arr_z):
        tqdm.write("loading DDI interaction data.")
        DDI_interaction_x = np.load(path_arr_x)
        DDI_interaction_y = np.load(path_arr_y)
        DDI_interaction_z = np.load(path_arr_z)
    else:
        tqdm.write("DDI files not found")
    #        break

    with state.State(f"input/LHF_DDI_glass_14_{concentration}_tunnel_{dim}.cfg", quiet = True) as p_state:
        types = geometry.get_atom_types(p_state)
        nos = types.size
        # tqdm.write(f"Sites: {nos}  Spins: {nos+np.sum(types)}")
        locs = geometry.get_positions(p_state)
        np.savetxt("output/"+prefix+"atom_locs.csv",locs,delimiter=",")
        np.savetxt("output/"+prefix+"atom_types.csv",types,delimiter=",")
    #    write_config(p_state,prefix)
        parameters.mc.set_metropolis_cone(p_state,use_cone=True,cone_angle=30,use_adaptive_cone=True)
        parameters.mc.set_metropolis_spinflip(p_state,False)

        parameters.mc.set_tunneling_gamma(p_state, tunneling_gamma=gamma)

        #We'll evaluate convergence after enough Metropolis steps to hit each site twitce on average
        parameters.mc.set_iterations(p_state,iterations_per_step*types.size,iterations_per_step*types.size)

        #Initialize from unordered state
        configuration.random(p_state)


    #Filter out any vacant sites
        vacancies_idx = np.where(types == -1)
        locs[:,0][vacancies_idx] = 0
        locs[:,1][vacancies_idx] = 0
        locs[:,2][vacancies_idx] = 0

        Hts_randomise = [8.0]*relax_steps_0
        #In Steven's paper sample was relaxed at high transverse field before negative
        # field cycle, probably to randomise the spins. But we should do this here anyways so config generated by configuration.random() align roughly along z-axis

        for i,Ht in enumerate(Hts_randomise):

            Hmag = Ht
            hamiltonian.set_field(p_state,Hmag,(Ht,0,0)) #Inside set_field, the vector is normalized, so we don't have to do that here

            spins = system.get_spin_directions(p_state)  #Get the current spin state to update the DDI fields from the Ewald sum
            spins[:, 2][vacancies_idx] = 0   #For LHF, we only care about Sz, but zero out the moments for vacancy site
            spins[:, 1][vacancies_idx] = 0
            spins[:, 0][vacancies_idx] = 0
            #Calculate the DDI field components, and then send to the SPIRIT engine. DDI interaction calculations are in Oe, SPIRIT
            #uses T, so need to scale accordingly.
            #Get the field at each spin.
            #V_xz = V_zx.T etc

            DDI_field_x_from_z = np.matmul(DDI_interaction_x,spins[:,2]) *7/1e4 #V_xz
            DDI_field_y_from_z = np.matmul(DDI_interaction_y,spins[:,2]) *7/1e4 #V_yz
            DDI_field_z_from_z = np.matmul(DDI_interaction_z,spins[:,2]) *7/1e4 #V_zz

            DDI_field_z_from_y = np.matmul(DDI_interaction_y.T, spins[:, 1]) * 7 / 1e4 #V_zy

            DDI_field_z_from_x = np.matmul(DDI_interaction_x.T, spins[:, 0]) * 7 / 1e4 #V_zx

            DDI_field_z_total = DDI_field_z_from_z + DDI_field_z_from_y + DDI_field_z_from_x

            #Pass into SPIRIT
            DDI_field_interleave = np.ravel(np.column_stack((DDI_field_x_from_z,DDI_field_y_from_z,DDI_field_z_total)))
            system.set_DDI_field(p_state,n_atoms=nos,ddi_fields=DDI_field_interleave)


            # for j in range(converge_max):
            simulation.start(p_state, simulation.METHOD_MC, single_shot=False) #solver_type=simulation.MC_ALGORITHM_METROPOLIS
            simulation.stop(p_state)


        # Hts = [H_relax]*H_relax_steps
        H1 = [H_high]*H_steps_1
        H2 = [H_low]*H_steps_1
        H3 = [H_high]*H_steps_3

        Hts = H1 + H2 + H3

        chis = []

        count = 0
        for k,Ht in enumerate(Hts):
            count+=1
            tqdm.write(f'Ht: {Ht:.3f}, count: {count} gamma: {gamma} concentration: {concentration}')

            hamiltonian.set_field(p_state,Ht,(Ht,0,0)) #Inside set_field, the vector is normalized, so we don't have to do that here

            spins = system.get_spin_directions(p_state)  #Get the current spin state to update the DDI fields from the Ewald sum
            spins[:,2][vacancies_idx] = 0   #For LHF, we only care about Sz, but zero out the moments for vacancy site
            spins[:, 1][vacancies_idx] = 0
            spins[:, 0][vacancies_idx] = 0
            #Calculate the DDI field components, and then send to the SPIRIT engine. DDI interaction calculations are in Oe, SPIRIT
            #uses T, so need to scale accordingly.
            #Get the field at each spin.
            #V_xz = V_zx.T etc

            DDI_field_x_from_z = np.matmul(DDI_interaction_x,spins[:,2]) *7/1e4 #V_xz
            DDI_field_y_from_z = np.matmul(DDI_interaction_y,spins[:,2]) *7/1e4 #V_yz
            DDI_field_z_from_z = np.matmul(DDI_interaction_z,spins[:,2]) *7/1e4 #V_zz

            DDI_field_z_from_y = np.matmul(DDI_interaction_y.T, spins[:, 1]) * 7 / 1e4 #V_zy

            DDI_field_z_from_x = np.matmul(DDI_interaction_x.T, spins[:, 0]) * 7 / 1e4 #V_zx

            DDI_field_z_total = DDI_field_z_from_z + DDI_field_z_from_y + DDI_field_z_from_x

            #Pass into SPIRIT
            DDI_field_interleave = np.ravel(np.column_stack((DDI_field_x_from_z,DDI_field_y_from_z,DDI_field_z_total)))
            system.set_DDI_field(p_state,n_atoms=nos,ddi_fields=DDI_field_interleave)


            # for j in range(converge_max):
            simulation.start(p_state, simulation.METHOD_MC, single_shot=False) #solver_type=simulation.MC_ALGORITHM_METROPOLIS
            simulation.stop(p_state)


            #Get spin states
            if k == H_steps_1 - 1 :
                spins = system.get_spin_directions(p_state)
                spin_z_before = spins[:,2]

                # Remove vacant site data from output arrays
                valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)

                spin_z_before = spin_z_before[valid_idx]

            if k == H_steps_1:
                spins = system.get_spin_directions(p_state)
                spin_z_lowH_before = spins[:,2]

                # Remove vacant site data from output arrays
                valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)

                spin_z_lowH_before = spin_z_lowH_before[valid_idx]

            if k == H_steps_1*2 :
                spins = system.get_spin_directions(p_state)
                spin_z_after = spins[:,2]

                # Remove vacant site data from output arrays
                valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)

                spin_z_after = spin_z_after[valid_idx]

            if k == H_steps_1*2 - 1:
                spins = system.get_spin_directions(p_state)
                spin_z_lowH_after = spins[:,2]

                # Remove vacant site data from output arrays
                valid_idx = np.setdiff1d(np.arange(spins.shape[0]), vacancies_idx)

                spin_z_lowH_after = spin_z_lowH_after[valid_idx]

    return spin_z_before, spin_z_after, spin_z_lowH_before, spin_z_lowH_after


if __name__ == '__main__':
    start_time = time.time()  # Start timer
    mp.set_start_method("spawn", force=True)

    n_cycles = 240

    H_high = 4.0
    H_low = 2.0

    dim = 4
    concentration = 20
    # gamma = 0.000001
    gamma = 1e-7
    gammas = [gamma]*n_cycles
    anisotropy = 1.5

    with mp.Pool(processes=mp.cpu_count()) as pool:
        results = list(tqdm(pool.imap_unordered(plot_loop, gammas), total=len(gammas), desc="Running simulations"))

    # Create a list to hold intermediate DataFrames
    dfs = []

    for before, after, before_lowH, after_lowH in results:
        df = pd.DataFrame({
            'spin_z_before': before,
            'spin_z_after': after,
            'spin_z_lowH_before': before_lowH,
            'spin_z_lowH_after': after_lowH,
        })
        dfs.append(df)

    # Concatenate all into a single DataFrame
    all_data = pd.concat(dfs, ignore_index=True)

    # Remove rows where abs(spin_z_before) > 1.01 or abs(spin_z_after) > 1.01
    all_data = all_data[
        (all_data['spin_z_before'].abs() <= 1.01) &
        (all_data['spin_z_after'].abs() <= 1.01) &
        (all_data['spin_z_lowH_before'].abs() <= 1.01) &
        (all_data['spin_z_lowH_after'].abs() <= 1.01)
        ]
    #
    all_data.to_csv(f"correlations_negative_field_cycle_dim{dim}_anisotropy{anisotropy}_ncycles{n_cycles}_gamma{gamma}_H_high{H_high}_H_low{H_low}.csv", index = False)
    #
    #
    # # Scatter plot with Plotly
    # fig = px.scatter(
    #     all_data,
    #     x='spin_z_before',
    #     y='spin_z_after',
    #     title="Spin Z After vs Before"
    # )

    x = all_data['spin_z_before']
    y = all_data['spin_z_after']

    # Compute 2D density
    xy = np.vstack([x, y])
    z = gaussian_kde(xy)(xy)

    # Add density to the DataFrame
    all_data['density'] = z

    # Plot colored scatter
    fig = px.scatter(
        all_data,
        x='spin_z_before',
        y='spin_z_after',
        color='density',
        color_continuous_scale='Viridis',
        title="Spin Z before change in H vs after decay in low H and right after rejuvenation (Density Colored)"
    )

    fig.write_html(f"correlations_negative_field_cycle_dim{dim}_anisotropy{anisotropy}_ncycles{n_cycles}_gamma{gamma}_H_high{H_high}_H_low{H_low}.html")

    # x = all_data['spin_z_before']
    # y = all_data['spin_z_lowH_before']
    #
    # # Compute 2D density
    # xy = np.vstack([x, y])
    # z = gaussian_kde(xy)(xy)
    #
    # # Add density to the DataFrame
    # all_data['density'] = z
    #
    # # Plot colored scatter
    # fig = px.scatter(
    #     all_data,
    #     x='spin_z_before',
    #     y='spin_z_lowH_before',
    #     color='density',
    #     color_continuous_scale='Viridis',
    #     title="Spin Z before vs right after drop in transverse field (Density Colored)"
    # )
    #
    # fig.write_html(
    #     f"correlations_1_negative_field_cycle_dim{dim}_anisotropy{anisotropy}_ncycles{n_cycles}_gamma{gamma}_H_high{H_high}_H_low{H_low}.html")

    x = all_data['spin_z_before']
    y = all_data['spin_z_lowH_after']

    # Compute 2D density
    xy = np.vstack([x, y])
    z = gaussian_kde(xy)(xy)

    # Add density to the DataFrame
    all_data['density'] = z

    # Plot colored scatter
    fig = px.scatter(
        all_data,
        x='spin_z_before',
        y='spin_z_lowH_after',
        color='density',
        color_continuous_scale='Viridis',
        title="Spin Z before change in H vs after decay in low H and before rejuvenation (Density Colored)"
    )

    fig.write_html(
        f"correlations_2_negative_field_cycle_dim{dim}_anisotropy{anisotropy}_ncycles{n_cycles}_gamma{gamma}_H_high{H_high}_H_low{H_low}.html")



